$ANSIBLE_VAULT;1.1;AES256
66626463323239633065613238343731326338616431396436616161383537333832646236323336
3966393235303932356435636139303364643261643766350a623061326638333033383238363334
61363732346231663861636137623162643665346632373664643639666331663762626561343739
3537386566373738660a356134623632343030306532326230623566636137393933356163323865
61333431636661363766313565383435633365386338396263623864636238303132626137323764
39336430363161373066303335623636663931646231373231636130333636346632396134626666
62353339613234643634616330613331313762633936636362656530313236376236316436653964
33393961346533386561356361383630366139333163326633303532663436396534643234386363
3737
