apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-agent-crb
roleRef:
  kind: ClusterRole
  name: jenkins-agent-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: jenkins-agent
    apiGroup: rbac.authorization.k8s.io